### ISSUE TITLE
Replace es5 function to es6 arrow function and remove console.log

### ISSUE THREAD

**Issue by KingAzizz** [KingAzizz/food-recipes-project#3]
in [food-recipes-project](https://github.com/KingAzizz/food-recipes-project)/[src](https://github.com/KingAzizz/food-recipes-project/tree/master/src)/[components](https://github.com/KingAzizz/food-recipes-project/tree/master/src/components)/Search.jsx 
/
<img width="472" alt="Screen Shot 2022-02-12 at 8 13 29 PM" src="https://user-images.githubusercontent.com/71937852/153721089-3c67fc68-b5e1-458e-a0b8-7cd24abe854e.png">

**Comment by raynardmiot** [comment]
✋

**Comment by raynardmiot** [comment]
Do you want me to remove all console.log from server.js?

**Comment by KingAzizz** [comment]
sure

**Comment by KingAzizz** [comment]
no leave it please

**Comment by raynardmiot** [comment]
ok! 👍👍
